apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-database
spec:
  template:
    spec:
      containers:
        - name: postgres
          image: postgres:9.6.19-alpine
          command: ["sh", "/files/migrate.sh"]
          envFrom:
            - secretRef:
                name: envvars
          volumeMounts:
            - name: files
              mountPath: /files
      restartPolicy: Never
      volumes:
        - name: files
          configMap:
            name: files
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: files
data:
  migrate.sh: |
    echo 'Starting Loading CKAN DB'
    wget $CKAN_CLOUD_CKAN_DUMP -O ckan.gz
    echo unziping
    gunzip ckan.gz
    echo unzipped
    ls ckan -al
    psql $DX_DEV_URI < ckan
    echo 'Starting load Datastore DB'
    wget $CKAN_CLOUD_DATASTORE_DUMP -O datastore.gz
    gunzip datastore.gz
    psql $DX_DEV_URI < datastore

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: envvars
stringData:
  CKAN_CLOUD_CKAN_DUMP: "https://storage.googleapis.com/cluster-backups-prod/gcloud_sql/2020/01/01/01/myinstance_202001010101.gz"
  # You can leave datastore URL empty if not required
  CKAN_CLOUD_DATASTORE_DUMP: "https://storage.googleapis.com/cluster-backups-prod/gcloud_sql/2020/01/01/01/myinstance-datastore_202001010101.gz"
  DX_DEV_URI: "postgresql://default:password@0.00.000.0:5432"
