name: Continuous Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Configure
      run: yarn install
    - name: Build
      run: yarn build:docs
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: .vuepress/dist
